# This file requires that you have the CamundaScriptingDelegatesProcessEnginePlugin-1.0.jar in the same directory as the docker-compose.yml

services:
  camunda-server:
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dgroovy.grape.report.downloads=true -Divy.message.logger.level=4"
    volumes:
      - ./CamundaScriptingDelegatesProcessEnginePlugin-1.1.0.jar:/camunda/configuration/userlib/CamundaScriptingDelegatesProcessEnginePlugin.jar
      - ./scripts:/scripts
      - ./camunda-beans.xml:/camunda/configuration/camunda-beans.xml
      - ./default.yml:/camunda/configuration/default.yml