spring:
  datasource:
    url: jdbc:h2:./build/DB/dbdevDb1;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE # jdbc:h2:~/devDb1;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password: ''

camunda:
  scriptingBeansXml: /camunda-beans.xml # Where the beans are configured
  scriptingEndpoint: true # Enables the endpoint for scripting usage
  scriptingEndpointRoot: "/api" # The root the scripting endpoint will be exposed at.  Defaults to /api
  bpm:
    admin-user:
      id: admin
      password: admin
    history-level: full
    job-execution:
      deployment-aware: false
    eventing:
      execution: true
      history: true
      task: true
  #spring:
#  jersey:
#    application-path: /rest